#!/usr/bin/env bash
# Regenerate src/std_freestanding.cppm by MEASURING which libc++ headers
# compile for a freestanding target — never by curating a list.
#
# ⚠️ Run this when the toolchain moves, and read the host control group it
# prints. Headers that fail here AND on the host are headers libc++ has not
# implemented; recording those as "bare metal cannot do it" is the mistake this
# script exists to make impossible.
#
#   tools/regenerate.sh <llvm-payload-dir> <picolibc-dir> [profile]
set -euo pipefail
LLVM="${1:?usage: regenerate.sh <llvm-dir> <picolibc-dir> [profile]}"
PICO="${2:?usage: regenerate.sh <llvm-dir> <picolibc-dir> [profile]}"
PROFILE="${3:-rv64gc/lp64d}"
ARCH="${PROFILE%%/*}"; ABI="${PROFILE##*/}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT
mkdir -p "$WORK/cfg/c++/v1"
sed -e 's/^#define _LIBCPP_HAS_THREADS .*/#define _LIBCPP_HAS_THREADS 0/' \
    -e 's/^#define _LIBCPP_HAS_MONOTONIC_CLOCK .*/#define _LIBCPP_HAS_MONOTONIC_CLOCK 0/' \
    -e 's/^#define _LIBCPP_HAS_FILESYSTEM .*/#define _LIBCPP_HAS_FILESYSTEM 0/' \
    -e 's/^#define _LIBCPP_HAS_LOCALIZATION .*/#define _LIBCPP_HAS_LOCALIZATION 0/' \
    -e 's/^#define _LIBCPP_HAS_TERMINAL .*/#define _LIBCPP_HAS_TERMINAL 0/' \
    -e 's/^#define _LIBCPP_HAS_RANDOM_DEVICE .*/#define _LIBCPP_HAS_RANDOM_DEVICE 0/' \
    -e 's/^#define _LIBCPP_HAS_TIME_ZONE_DATABASE .*/#define _LIBCPP_HAS_TIME_ZONE_DATABASE 0/' \
    -e 's/^#define _LIBCPP_HAS_WIDE_CHARACTERS .*/#define _LIBCPP_HAS_WIDE_CHARACTERS 0/' \
    -e 's/^#define _LIBCPP_LIBC_PICOLIBC .*/#define _LIBCPP_LIBC_PICOLIBC 1/' \
    -e 's/^#define _LIBCPP_PSTL_BACKEND_STD_THREAD/#define _LIBCPP_PSTL_BACKEND_SERIAL/' \
    "$LLVM"/include/*/c++/v1/__config_site > "$WORK/cfg/c++/v1/__config_site"

: > "$WORK/ok"; : > "$WORK/bad"
for inc in "$LLVM"/share/libc++/v1/std/*.inc; do
    h="$(basename "$inc" .inc)"
    printf '#include <%s>\nint main(){return 0;}\n' "$h" > "$WORK/t.cpp"
    if "$LLVM/bin/clang++" --target=riscv64-none-elf -march="$ARCH" -mabi="$ABI" \
        -mcmodel=medany -std=c++23 -ffreestanding -fno-exceptions -fno-rtti \
        -nostdinc++ --no-default-config -isystem "$WORK/cfg/c++/v1" \
        -isystem "$LLVM/include/c++/v1" -isystem "$PICO/include/$PROFILE" \
        -fsyntax-only "$WORK/t.cpp" >/dev/null 2>&1
    then echo "$h" >> "$WORK/ok"; else echo "$h" >> "$WORK/bad"; fi
done
echo "compiles for $PROFILE: $(wc -l < "$WORK/ok") / $(ls "$LLVM"/share/libc++/v1/std/*.inc | wc -l)"

# ⭐ The control group. Without it the next line is unreadable.
echo "── the ones that failed, retried on THIS host with full libc++ ──"
while read -r h; do
    printf '#include <%s>\nint main(){return 0;}\n' "$h" > "$WORK/h.cpp"
    if "$LLVM/bin/clang++" -std=c++23 -stdlib=libc++ -fsyntax-only "$WORK/h.cpp" >/dev/null 2>&1
    then echo "  $h: HOST OK   ← a real freestanding loss"
    else echo "  $h: host fails too (libc++ has not implemented it)"; fi
done < "$WORK/bad"

{
  echo "// mcpplibs.std.freestanding — the freestanding subset of the standard library."
  echo "//"
  echo "// GENERATED by tools/regenerate.sh. The list is not a curated opinion: it is"
  echo "// every libc++ header that compiles for a freestanding target, measured by"
  echo "// compiling each one."
  echo "//"
  echo "// ⚠️ The export table is NOT here and must never be written here. libc++ ships"
  echo "// one \`std/<header>.inc\` per header — each \`export namespace std { using"
  echo "// std::X; }\` — and maintains them. This file only SELECTS."
  echo "module;"
  sed 's|^|#include <|; s|$|>|' "$WORK/ok"
  echo "export module mcpplibs.std.freestanding;"
  sed 's|^|#include "std/|; s|$|.inc"|' "$WORK/ok"
} > "$ROOT/src/std_freestanding.cppm"
echo "wrote src/std_freestanding.cppm"
