// mcpplibs.std.freestanding — the freestanding subset of the standard library.
//
// GENERATED by tools/regenerate.sh. The list is not a curated opinion: it is
// every libc++ header that compiles for a freestanding target, measured by
// compiling each one.
//
// ⚠️ NINE HEADERS ARE GUARDED BY `MCPP_FEATURE_NOLIBC`, AND THE LIST IS MEASURED.
//
// On a target whose `[target.<triple>].sysroot` is empty there is no C library
// at all. 94 of the 103 headers below still compile — the `nolibc` feature
// supplies the four C headers libc++'s own wrappers reach for — but nine want a
// real one (`cmath` wants the math library's declarations, `cstdlib` its
// allocator and process control, `format` and `print` its I/O). Those nine are
// compiled out rather than left to fail, and their export tables with them: an
// export table naming declarations that are absent is an error in the module
// interface, not in the consumer.
//
// ⚠️ The export table is NOT here and must never be written here. libc++ ships
// one `std/<header>.inc` per header — each `export namespace std { using
// std::X; }` — and maintains them. This file only SELECTS.
module;
#include <algorithm>
#include <any>
#include <array>
#include <atomic>
#include <barrier>
#include <bit>
#include <bitset>
#include <cassert>
#include <cctype>
#include <cerrno>
#include <cfenv>
#include <cfloat>
#include <charconv>
#include <chrono>
#ifndef MCPP_FEATURE_NOLIBC
#include <cinttypes>
#endif
#include <climits>
#include <clocale>
#ifndef MCPP_FEATURE_NOLIBC
#include <cmath>
#endif
#include <codecvt>
#include <compare>
#ifndef MCPP_FEATURE_NOLIBC
#include <complex>
#endif
#include <concepts>
#include <condition_variable>
#include <coroutine>
#include <csetjmp>
#include <csignal>
#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#ifndef MCPP_FEATURE_NOLIBC
#include <cstdlib>
#endif
#include <cstring>
#include <ctime>
#include <cuchar>
#include <cwchar>
#include <cwctype>
#include <deque>
#ifndef MCPP_FEATURE_NOLIBC
#include <exception>
#endif
#include <execution>
#include <expected>
#include <filesystem>
#include <flat_map>
#include <flat_set>
#ifndef MCPP_FEATURE_NOLIBC
#include <format>
#endif
#include <forward_list>
#include <fstream>
#include <functional>
#include <future>
#include <initializer_list>
#include <iomanip>
#include <iosfwd>
#include <ios>
#include <iostream>
#include <istream>
#include <iterator>
#include <latch>
#include <limits>
#include <list>
#include <locale>
#include <map>
#include <mdspan>
#include <memory>
#include <memory_resource>
#include <mutex>
#include <new>
#include <numbers>
#include <numeric>
#include <optional>
#include <ostream>
#ifndef MCPP_FEATURE_NOLIBC
#include <print>
#endif
#include <queue>
#ifndef MCPP_FEATURE_NOLIBC
#include <random>
#endif
#include <ranges>
#include <ratio>
#include <regex>
#include <scoped_allocator>
#include <semaphore>
#include <set>
#include <shared_mutex>
#include <source_location>
#include <span>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <stop_token>
#include <streambuf>
#include <string>
#include <string_view>
#include <strstream>
#include <syncstream>
#include <system_error>
#include <thread>
#include <tuple>
#include <typeindex>
#include <typeinfo>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#ifndef MCPP_FEATURE_NOLIBC
#include <valarray>
#endif
#include <variant>
#include <vector>
#include <version>
export module mcpplibs.std.freestanding;
#include "std/algorithm.inc"
#include "std/any.inc"
#include "std/array.inc"
#include "std/atomic.inc"
#include "std/barrier.inc"
#include "std/bit.inc"
#include "std/bitset.inc"
#include "std/cassert.inc"
#include "std/cctype.inc"
#include "std/cerrno.inc"
#include "std/cfenv.inc"
#include "std/cfloat.inc"
#include "std/charconv.inc"
#include "std/chrono.inc"
#ifndef MCPP_FEATURE_NOLIBC
#include "std/cinttypes.inc"
#endif
#include "std/climits.inc"
#include "std/clocale.inc"
#ifndef MCPP_FEATURE_NOLIBC
#include "std/cmath.inc"
#endif
#include "std/codecvt.inc"
#include "std/compare.inc"
#ifndef MCPP_FEATURE_NOLIBC
#include "std/complex.inc"
#endif
#include "std/concepts.inc"
#include "std/condition_variable.inc"
#include "std/coroutine.inc"
#include "std/csetjmp.inc"
#include "std/csignal.inc"
#include "std/cstdarg.inc"
#include "std/cstddef.inc"
#include "std/cstdint.inc"
#include "std/cstdio.inc"
#ifndef MCPP_FEATURE_NOLIBC
#include "std/cstdlib.inc"
#endif
#include "std/cstring.inc"
#include "std/ctime.inc"
#include "std/cuchar.inc"
#include "std/cwchar.inc"
#include "std/cwctype.inc"
#include "std/deque.inc"
#ifndef MCPP_FEATURE_NOLIBC
#include "std/exception.inc"
#endif
#include "std/execution.inc"
#include "std/expected.inc"
#include "std/filesystem.inc"
#include "std/flat_map.inc"
#include "std/flat_set.inc"
#ifndef MCPP_FEATURE_NOLIBC
#include "std/format.inc"
#endif
#include "std/forward_list.inc"
#include "std/fstream.inc"
#include "std/functional.inc"
#include "std/future.inc"
#include "std/initializer_list.inc"
#include "std/iomanip.inc"
#include "std/iosfwd.inc"
#include "std/ios.inc"
#include "std/iostream.inc"
#include "std/istream.inc"
#include "std/iterator.inc"
#include "std/latch.inc"
#include "std/limits.inc"
#include "std/list.inc"
#include "std/locale.inc"
#include "std/map.inc"
#include "std/mdspan.inc"
#include "std/memory.inc"
#include "std/memory_resource.inc"
#include "std/mutex.inc"
#include "std/new.inc"
#include "std/numbers.inc"
#include "std/numeric.inc"
#include "std/optional.inc"
#include "std/ostream.inc"
#ifndef MCPP_FEATURE_NOLIBC
#include "std/print.inc"
#endif
#include "std/queue.inc"
#ifndef MCPP_FEATURE_NOLIBC
#include "std/random.inc"
#endif
#include "std/ranges.inc"
#include "std/ratio.inc"
#include "std/regex.inc"
#include "std/scoped_allocator.inc"
#include "std/semaphore.inc"
#include "std/set.inc"
#include "std/shared_mutex.inc"
#include "std/source_location.inc"
#include "std/span.inc"
#include "std/sstream.inc"
#include "std/stack.inc"
#include "std/stdexcept.inc"
#include "std/stop_token.inc"
#include "std/streambuf.inc"
#include "std/string.inc"
#include "std/string_view.inc"
#include "std/strstream.inc"
#include "std/syncstream.inc"
#include "std/system_error.inc"
#include "std/thread.inc"
#include "std/tuple.inc"
#include "std/typeindex.inc"
#include "std/typeinfo.inc"
#include "std/type_traits.inc"
#include "std/unordered_map.inc"
#include "std/unordered_set.inc"
#include "std/utility.inc"
#ifndef MCPP_FEATURE_NOLIBC
#include "std/valarray.inc"
#endif
#include "std/variant.inc"
#include "std/vector.inc"
#include "std/version.inc"
